repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4  # Usa la versión estable más reciente de Ruff
    hooks:
      - id: ruff
        args: [--fix]        # Lint + autofix
      - id: ruff-format      # Formateo de código

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: detect-private-key
      - id: check-added-large-files

  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
    - id: mypy
      additional_dependencies:
      - "types-pymysql>=1.1.0"

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.7
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml", "-r", "."]
        additional_dependencies: ["bandit[toml]"]

  # - repo: local
  #   hooks:
  #     - id: pytest
  #       name: pytest
  #       entry: bash -c "pytest -W ignore --maxfail=1 --disable-warnings || true"
  #       language: system
  #       pass_filenames: false
  #       always_run: true
